### ISSUE TITLE
Provide simpler use case for using Relaton IEV

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-iev#1]
We need a simpler use case of using Relaton IEV. We should use the IEV gem to fetch terms (via term ID), and Relaton IEV for generating the reference.

Right now the README gives this example which is too complex:

```rb
require 'relaton_iev'

bibdb = Relaton::Db.new nil, nil
xmldoc = Nokogiri::XML <<~XML_DOC
      <standard-document>
        <bibitem type="inline" bibitemid="a" docidentifier="IEC 60050:2011">
          <eref citeas="IEC 60050:2011">
            <locality type="clause">
            <referenceFrom>102-01-01</referenceFrom>
            </locality>
          </eref>
        </bibitem>
        <sections/>
      </standard-document>
    XML_DOC
RelatonIev.iev_cleanup(xmldoc, bibdb)
=> [#<Nokogiri::XML::Element:...
```

**Comment by andrew2net** [comment]
Seems I don't have a complete view of the task.
[Here](https://github.com/metanorma/metanorma-standoc/issues/21) given just 3 functions to extract from `metanorma-standic`. The function `iev_cleanup` needs a `Nokogiri::XML::Document` as argument.
Suppose the gem should be something like `relaton-iec`. If so then what is the difference between `relaton-iev` and `relaton-iec`?

**Comment by opoudjis** [comment]
This is not a discussion that should be held without me (because this is metanorma code, not relaton code), and I am not seeing what the use of simplifying anything is. The use case is refactoring metanorma-standoc code to handle postprocessing of IEV references externally; there is no end user facing functionality. 

I am not going to refactor all code processing all references in case there is an IEV reference there, when rewriting them at the end is working fine. The code is fragile enough without this kind of refactoring.
